spring.application.name=notificacionincidencias
spring.datasource.url=jdbc:postgresql://dpg-d4k2no24d50c73d7oh5g-a.oregon-postgres.render.com:5432/incidencias_dae_99b1
spring.datasource.username=admin
spring.datasource.password=MyvkgiszvquobcjpwyDknN2IxmBysEJt

spring.jpa.properties.jakarta.persistence.schema-generation.database.action: update
