spring.application.name=notificacionincidencias
spring.datasource.url: jdbc:postgresql://dpg-d3vsh7muk2gs73b1g6b0-a.frankfurt-postgres.render.com:5432/incidencias_dae
spring.datasource.username: admin
spring.datasource.password: dqXw4yIwHWEMX0AQ5dTYcIIIxc1UsNTg

spring.jpa.properties.jakarta.persistence.schema-generation.database.action: none
